name: Quality Check

on:
  push:
  pull_request:
    branches: [main]

jobs:
  quality_check:
    name: Quality Check
    runs-on: figure-linux-standard
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Check Code Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check Clippy Recommendations
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run Contract Tests
        run: make test

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          server-id: github

      # Will automatically verify ktlint and run tests
      - name: Build Kotlin-Tools
        run: ./kotlin-tools/gradlew clean build --refresh-dependencies --project-dir ./kotlin-tools
